config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :questions, except: [:edit, :update] do
    get :feed, to: 'questions#feed', on: :collection
    get :get_shorten_link, to: 'questions#get_shorten_link'
    resources :answers
    post :send_sms, on: :collection
  end
  root 'questions#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_question, only: [:index, :new, :create]
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_client, only: [:create]

  def index
    @answers = @question.answers.reverse
  end

  def show
  end

  def new
    @answer = Answer.new
  end

  def edit
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.question_id = params[:question_id]

    if @answer.save
      @client.messages.create(
        from: ENV["TWILIO_PHONE_NUMBER"],
        to:   @question.phone_number,
        body: @answer.text
      )
      redirect_to question_answers_url(@question), notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer, notice: 'Answer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to answers_url, notice: 'Answer was successfully destroyed.'
  end

  private
    def set_client
      @client = Twilio::REST::Client.new
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_question
      @question = Question.find(params[:question_id])
    end

    def answer_params
      params.require(:answer).permit(:user_id, :text)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.slim
= form_for [:question, @answer] do |f|
  - if @answer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      ul
        - @answer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :text, "Answer"
    br
    = f.text_field :text
  .actions = f.submit

app/views/answers/edit.html.slim
h1 Editing answer

== render 'form'

= link_to 'Show', @answer
'|
= link_to 'Back', question_answers_path

app/views/answers/index.html.slim
h2 = @question.message

- @answers.each do |answer|
  .question
    .box
      .phone_number= answer.created_at.strftime("%d-%m-%Y / %H:%M")
      .message= answer.text

.btn.center= link_to 'New Answer', new_question_answer_path

app/views/answers/new.html.slim
h1 = @question.message

== render 'form'

p: .btn.center= link_to 'Back', questions_path

app/views/answers/show.html.slim
p#notice = notice

p
  strong User:
  = @answer.user
p
  strong Text:
  = @answer.text

.btn.center= link_to 'Back', question_answers_path